import numpy as np

# question - 1
# print("Total Revenue Generated By two products : ")
# cat1 = np.array([500,600,700,550])
# cat2 = np.array([450,700,800,600])
# print(cat1+cat2)

# question - 2
# print("Profit made by a company : ")
# cat1 = np.array([10000,12000,11000,10500])
# cat2 = np.array([4000,5000,4500,4800])
# print(cat1-cat2)


# question - 3
# print("Out Of stock Products : ")
# inventory = np.array([10,0,5,0,20,0])

# outOfStock = inventory[inventory == 0]
# print(outOfStock)

# question - 4
# print("Total cost of items : ")
# quantity = np.array([2,3,4,1])
# price_per_item = np.array([10.0,5.0,8.0,12.0])

# print(quantity*price_per_item)